# Generated by Django 4.1.1 on 2022-12-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
